### ISSUE TITLE
Can handy-spanner Support DML?

### ISSUE THREAD

**Issue by lryong** [gcpug/handy-spanner#40]
My project needs to simulate a offline spanner, but except handy-spanner, I can't find a better solution at present.However, it  fully not yet supported DML.

Can handy-spanner support DML or is there any plans to support DML in the future?

**Comment by kazegusuri** [comment]
yes. Now I'm trying to support transactions. I will try to support DML after that.
Since handy spanner uses sqlite3 as backend and there are limitations around transactions in sqlite3, spanner transaction cannot be fully simulated. So DML also has limitations in the transaction.

**Comment by kazegusuri** [comment]
I have implemented DML features with transaction in `transaction` branch. When I confirm the branch in internal use cases, I merge the branch to `master`. You can try the branch though. If you have issues, reports are welcome.

**Comment by kazegusuri** [comment]
I merged  a PR that implements DML feature, so close this issue. If you have another issue feel free to create an issue.

**Comment by lryong** [comment]
But  still not implemented ExecuteSql  yet.  I rely on this  feature and have not solved my problem.

**Comment by kazegusuri** [comment]
What do you mean? DML is implemented in ExecuteSql and ExecuteBatchDml methods. Do Now ExecuteSql is only for DML. Do you expect to support query in ExecuteSQL as well?

**Comment by lryong** [comment]
Sorry, I seriously looked at the error log and found that an error occurred `not implemented yet: ExecuteSql"` while executing my function. 
I searched the entire project and found that only the `GetDatabaseDdl` function of the handy-spanner would return this error.

**Comment by kazegusuri** [comment]
If you saw that the version of handy-spanner you used is old. The latest version implements ExecuteSql method

**Comment by lryong** [comment]
OK, but thanks a lot.
